#!/bin/sh
ABSPATH=$(readlink $0)
BASEDIR=$(dirname $ABSPATH)
if [ ! -d "$BASEDIR/node_modules" ]; then
	npm install $BASEDIR
fi
$BASEDIR/node_modules/grunt-cli/bin/grunt --gruntfile "$BASEDIR/Gruntfile.js" run-chrome