#!/bin/sh
ABSPATH=$(readlink -f $0)
echo $ABSPATH
BASEDIR=$(dirname $ABSPATH)
if [ ! -d "$BASEDIR/node_modules" ]; then
	npm install $BASEDIR --production
fi
$BASEDIR/node_modules/grunt-cli/bin/grunt --gruntfile "$BASEDIR/Gruntfile.js" chrome